### ISSUE TITLE
Ensure all provided clients are provided based on endpoint uris

### ISSUE THREAD

**Issue by applike-ss** [justtrackio/gosoline#379]
We should provide clients based on endpoint uris instead of using a singleton approach.

https://github.com/applike/gosoline/pull/378 is the first one because it was needed in an integration test scenario, however all kind of clients should be provided like this.

Research which clients exist and how we can provide them based on their uri.

**Comment by ajscholl** [comment]
I guess this is done with the AWS v2 changes?

**Comment by applike-ss** [comment]
yeah, i think so. Thanks!
