### ISSUE TITLE
Update aws-go-sdk version to V2

### ISSUE THREAD

**Issue by applike-ss** [justtrackio/gosoline#410]
See this for migration notes: https://aws.github.io/aws-sdk-go-v2/docs/migrating

Advantages: 
* Better performance (read of up to 50%)
* more modular => less code to compile => faster compile time

**Comment by j4k4** [comment]
I'll started looking into the integration of the new sdk :+1:

**Comment by applike-ss** [comment]
closed by #595 and #602
