### ISSUE TITLE
bump gin-contrib/gzip to 0.0.4

### ISSUE THREAD

**Issue by ss89** [justtrackio/gosoline#652]
gin-contribs gzip implemetation does behave wrong when it comes to sse in 0.0.3.

That is fixed in 0.0.4, as the header that was used for checking if the contents may be compressed or not was corrected.

see: https://github.com/gin-contrib/gzip/pull/31

**Comment by ajscholl** [comment]
I think we are at 0.0.5 already, can we close this @ss89?

**Comment by applike-ss** [comment]
yap, will close this
